### PR TITLE
very small

### PR DESCRIPTION
**Pull request by realpack**

### CODE REVIEW

**Comment by PartialDevAdmin** [comment]
@realpack You should say what this PR does. This PR fixes an error in the Russian locale file.

**Comment by realpack** [comment]
@PartialDevAdmin I thought that this was unnecessary torment. There are very few changes in this PR.

**Comment by PartialDevAdmin** [comment]
@realpack Yes, but it is always good to list what a PR does. I am thinking of forking this extension and making some improvements, and I will keep you posted. I want to ask @sijad's permission first

**Comment by sijad** [comment]
Thanks for your contribution.

@PartialDevAdmin sure you can, please let me know if I can help.

**Comment by PartialDevAdmin** [comment]
Sure thing!

**Pull request merged**
